### ISSUE TITLE
ModuleNotFoundError: No module named 'django_logging'

### ISSUE THREAD

**Issue by elcolie** [cipriantarta/django-logging#12]
After I follow the installation I got `ModuleNotFoundError: No module named 'django_logging'`
**Software:**
Python3.6.2
Django1.11

**Comment by cipriantarta** [comment]
Did you add “django_logging” in your INSTALLED_APPS ?

**Comment by elcolie** [comment]
```bash
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/el/.pyenv/versions/soken/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/el/.pyenv/versions/soken/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/el/.pyenv/versions/soken/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/el/.pyenv/versions/soken/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/el/.pyenv/versions/soken/lib/python3.6/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/Users/el/.pyenv/versions/3.6.2/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/el/.pyenv/versions/soken/lib/python3.6/site-packages/django_logging/__init__.py", line 1, in <module>
    from . import handlers
  File "/Users/el/.pyenv/versions/soken/lib/python3.6/site-packages/django_logging/handlers.py", line 7, in <module>
    from . import settings
  File "/Users/el/.pyenv/versions/soken/lib/python3.6/site-packages/django_logging/settings.py", line 51, in <module>
    sys.modules[__name__] = DjangoLoggingSettings()
  File "/Users/el/.pyenv/versions/soken/lib/python3.6/site-packages/django_logging/settings.py", line 33, in __init__
    self.__settings['LOG_PATH'] = os.path.join(django_settings.BASE_DIR, 'logs')
  File "/Users/el/.pyenv/versions/3.6.2/lib/python3.6/posixpath.py", line 78, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not Path
```
My bad. Here is the new error

**Comment by elcolie** [comment]
Here is my `LOGGING`. In case it might conflict with your package.
```python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'standard': {
            'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt': "%d/%b/%Y %H:%M:%S"
        },
    },
    'handlers': {
        'logfile': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR) + "/logfile",
            'maxBytes': 50000,
            'backupCount': 2,
            'formatter': 'standard',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'standard'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'logfile'],
            'propagate': True,
            'level': 'INFO',
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    }
}
```

**Comment by cipriantarta** [comment]
What’s the value for django_settings.BASE_DIR 
?

**Comment by elcolie** [comment]
It is `<Path:/Users/el/Code/norak-cutter/soken/soken-web/soken_web>`

**Comment by cipriantarta** [comment]
It needs to be a string, not a `path` object. Here’s what I use in my current project:
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

**Comment by cipriantarta** [comment]
Alas, we can add a change request to support paths as well

**Comment by elcolie** [comment]
Are you going to fix this now?
Otherwise I would ask for workaround on this problem

**Comment by cipriantarta** [comment]
Don’t have time right now.

You can set:
DJANGO_LOGGING = {
    “LOG_PATH": "C:\<some dir>"
}

Or change your BASE_DIR in settings.py as I’ve shown earlier.

**Comment by elcolie** [comment]
I just change your code according to my `PR`. It works.
