### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by codewiseio** [cipriantarta/django-logging#5]
I receive the following error when starting the development server after adding django logging to installed apps and to the middleware section of the settings.py file. 

Environment
Windows 10
Python 3.5.2
Django 1.10.2

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001AF6A17ED08>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\management\commands\runserver.py", line 142, in inner_run
    handler = self.get_handler(*args, **options)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\django\contrib\staticfiles\management\commands\runserver.py", line 27, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\management\commands\runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\servers\basehttp.py", line 49, in get_internal_wsgi_application
    return import_string(app_path)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\django\utils\module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\dev\django\classregistration\classregistration\wsgi.py", line 17, in
<module>
    application = get_wsgi_application()
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\wsgi.py", line 153, in __init__
    self.load_middleware()
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 82, in load_middleware

**Comment by cipriantarta** [comment]
That's interesting. Does it work if you remove django_logging from installed apps and middleware?
Is this a fresh django app?
Please add the INSTALLED_APPS part of your settings file and the MIDDLEWARE section as well.
I haven't tested the library in Windows, but I'll give it a try today.

**Comment by cipriantarta** [comment]
No input from the reporter for a long time, so closing this.
